# Generated by Django 4.0.4 on 2022-06-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About page', 'verbose_name_plural': 'About pages'},
        ),
    ]
