# Generated by Django 4.0.4 on 2022-05-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='reply',
            name='author_email',
            field=models.EmailField(default='user', max_length=254),
            preserve_default=False,
        ),
    ]
