# Generated by Django 4.0.4 on 2022-06-01 16:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Your blog post content. You can add headers, links, numbered lists and bullet points, images, embedded content, etc. ', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Choose a cover image for your blog post to feature on your home page and post category lists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False, help_text='If featured, the published post will be displayed on the home page. Only the latest 4 featured posts will be displayed.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, help_text='Write a short summary (max 255 characters) for your blog post. If left empty, the summary will be replaced by the start of the blog post body. ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
