# Generated by Django 4.0.4 on 2022-06-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0002_alter_blogpost_body_alter_blogpost_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ForeignKey(help_text='Choose a cover image for your blog post to feature on your home page and post category lists.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
