# Generated by Django 4.0.4 on 2022-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bloglistingpage_blogposttag_blogpost_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
