# Generated by Django 4.0.4 on 2022-05-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
