# Generated by Django 4.0.4 on 2022-05-25 13:23

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
