# Generated by Django 4.0.4 on 2022-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_picture_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='users/'),
        ),
    ]
